// Customers
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';

// Ads
export const GET_ADS_SUCCESS = 'GET_ADS_SUCCESS';
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS';