// Customers
export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL';

// Ads
export const GET_ADS_REQUEST = 'GET_ADS_REQUEST';
export const GET_ADS_SUCCESS = 'GET_ADS_SUCCESS';
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS';
export const SET_SELECTED_ADS = 'SET_SELECTED_ADS';

// Checkout
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';